spring.application.name=ileri_java

# Config Port
server.port=8090

# Config DB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:~/ileri_java;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=sa

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

